lib/banamex_web/router.ex
defmodule BanamexWeb.Router do
  use BanamexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BanamexWeb do
    pipe_through :browser
    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
    resources "/users", UserController
    resources "/cuentas", CuentaController
    get "/cuentas/transaction/:id" , CuentaController, :edit2
    resources "/cajeros", CajeroController
    resources "/atm", AtmController
    get "/call/id=:id", CallCenterController, :show
    resources "/call", CallCenterController
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BanamexWeb do
  #   pipe_through :api
  # end
end

lib/banamex_web/views/layout_view.ex
defmodule BanamexWeb.LayoutView do
  use BanamexWeb, :view
end

lib/banamex_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Banamex · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if logged_in?(@conn) do %>
        <span class="badge badge-dark mr-2"><%= current_user(@conn).username %></span>
        <%= link "Logout", to: Routes.session_path(@conn, :delete), method: :delete, class: "btn btn-secondary" %>
      <% else %>
        <%= link "Login", to: Routes.session_path(@conn, :new), class: "btn btn-primary" %>
        <%= link "Register", to: Routes.user_path(@conn, :new), class: "btn btn-secondary" %>
      <% end %>
          </ul>
        </nav>
        <a href="/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>