lib/banamex_web/router.ex
defmodule BanamexWeb.Router do
  use BanamexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BanamexWeb do
    pipe_through :browser
    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
    resources "/users", UserController
    resources "/cuentas", CuentaController
    get "/cuentas/transaction/:id" , CuentaController, :edit2
    resources "/cajeros", CajeroController
    resources "/atm", AtmController
    get "/call/id=:id", CallCenterController, :show
    resources "/call", CallCenterController
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BanamexWeb do
  #   pipe_through :api
  # end
end

lib/banamex/cajeros.ex
defmodule Banamex.Cajeros do
  @moduledoc """
  The Cajeros context.
  """

  import Ecto.Query, warn: false
  alias Banamex.Repo

  alias Banamex.Cajeros.Cajero

  @doc """
  Returns the list of cajeros.

  ## Examples

      iex> list_cajeros()
      [%Cajero{}, ...]

  """
  def list_cajeros do
    Repo.all(Cajero)
  end

  @doc """
  Gets a single cajero.

  Raises `Ecto.NoResultsError` if the Cajero does not exist.

  ## Examples

      iex> get_cajero!(123)
      %Cajero{}

      iex> get_cajero!(456)
      ** (Ecto.NoResultsError)

  """
  def get_cajero!(id), do: Repo.get!(Cajero, id)

  @doc """
  Creates a cajero.

  ## Examples

      iex> create_cajero(%{field: value})
      {:ok, %Cajero{}}

      iex> create_cajero(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_cajero(attrs \\ %{}) do
    %Cajero{}
    |> Cajero.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a cajero.

  ## Examples

      iex> update_cajero(cajero, %{field: new_value})
      {:ok, %Cajero{}}

      iex> update_cajero(cajero, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_cajero(%Cajero{} = cajero, attrs) do
    cajero
    |> Cajero.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Cajero.

  ## Examples

      iex> delete_cajero(cajero)
      {:ok, %Cajero{}}

      iex> delete_cajero(cajero)
      {:error, %Ecto.Changeset{}}

  """
  def delete_cajero(%Cajero{} = cajero) do
    Repo.delete(cajero)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking cajero changes.

  ## Examples

      iex> change_cajero(cajero)
      %Ecto.Changeset{source: %Cajero{}}

  """
  def change_cajero(%Cajero{} = cajero) do
    Cajero.changeset(cajero, %{})
  end
end

lib/banamex/cajeros/cajero.ex
defmodule Banamex.Cajeros.Cajero do
  use Ecto.Schema
  import Ecto.Changeset

  schema "cajeros" do
    field :deposito, :integer
    field :retiro, :integer
    field :saldo, :float

    timestamps()
  end

  @doc false
  def changeset(cajero, attrs) do
    cajero
    |> cast(attrs, [:saldo, :retiro, :deposito])
    |> validate_required([:saldo, :retiro, :deposito])
  end
end

lib/banamex_web/controllers/cajero_controller.ex
defmodule BanamexWeb.CajeroController do
  use BanamexWeb, :controller
  import Ecto.Query
  import Ecto.Repo
  alias Banamex.Cajeros
  alias Banamex.Cajeros.Cajero

  def index(conn, _params) do
    if Banamex.Accounts.Auth.logged_in?(conn) do

     current = Banamex.Accounts.Auth.current_user(conn)

      c = from u in "cuentas",
                where: u.user_id == ^current.id,
                select: [u.id,u.no_cta]
      cajeros = Banamex.Repo.all(c)
      render(conn, "index.html", cajeros: cajeros)
    else
      render(conn,"no_auth.html")
    end
  end

  def new(conn, _params) do
    changeset = Cajeros.change_cajero(%Cajero{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"cajero" => cajero_params}) do
    case Cajeros.create_cajero(cajero_params) do
      {:ok, cajero} ->
        conn
        |> put_flash(:info, "Cajero created successfully.")
        |> redirect(to: Routes.cajero_path(conn, :show, cajero))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    cajero = Cajeros.get_cajero!(id)
    render(conn, "show.html", cajero: cajero)
  end

  def edit(conn, %{"id" => id}) do
    cajero = Cajeros.get_cajero!(id)
    changeset = Cajeros.change_cajero(cajero)
    render(conn, "edit.html", cajero: cajero, changeset: changeset)
  end

  def update(conn, %{"id" => id, "cajero" => cajero_params}) do
    cajero = Banamex.Cuentas.get_cuenta!(id)
    if cajero.saldo < 100 do
      render(conn, "error.html", cajero: cajero)
    else 
      case Cajeros.update_cajero(cajero, cajero_params) do
        {:ok, cajero} ->
          conn
          |> put_flash(:info, "Cajero updated successfully.")
          |> redirect(to: Routes.cajero_path(conn, :show, cajero))
  
        {:error, %Ecto.Changeset{} = changeset} ->
          render(conn, "edit.html", cajero: cajero, changeset: changeset)
      end
    end
  end

  def delete(conn, %{"id" => id}) do
    cajero = Cajeros.get_cajero!(id)
    {:ok, _cajero} = Cajeros.delete_cajero(cajero)

    conn
    |> put_flash(:info, "Cajero deleted successfully.")
    |> redirect(to: Routes.cajero_path(conn, :index))
  end
end

lib/banamex_web/views/cajero_view.ex
defmodule BanamexWeb.CajeroView do
  use BanamexWeb, :view
end

lib/banamex_web/templates/cajero/edit.html.eex
<h1>Edit Cajero</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.cajero_path(@conn, :update, @cajero)) %>

<span><%= link "Back", to: Routes.cajero_path(@conn, :index) %></span>

lib/banamex_web/templates/cajero/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
  <%= label f, :saldo %>
  <%= number_input f, :saldo %>
  <%= error_tag f, :saldo %>
  
  <%= label f, :retiro %>
  <%= number_input f, :retiro %>
  <%= error_tag f, :retiro %>

  <%= label f, :deposito %>
  <%= number_input f, :deposito %>
  <%= error_tag f, :deposito %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/banamex_web/templates/cajero/index.html.eex
<h1>Listing Cajeros</h1>

<table>
  <thead>
    <tr>
      <th>Cuenta</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for [id,cta] <- @cajeros do %>
    <tr>
     
      <td><%= cta%></td>
       <td><%= link "Transacion", to:  Routes.cuenta_path(@conn, :edit2, id) %></td>
     </tr>
<% end %>
  </tbody>
</table>

<section class="row">
  <article class="column">
<h1> 
  <a href="/"> Inicio</a>
</h1>
  </article>
</section>

lib/banamex_web/templates/cajero/new.html.eex
<h1>New Cajero</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.cajero_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.cajero_path(@conn, :index) %></span>

lib/banamex_web/templates/cajero/no_auth.html.eex
<h1>
No esta Autorizado!
Por favor <a href="/login"> Inicie Sesión</a>
</h1>

lib/banamex_web/templates/cajero/show.html.eex
<h1>Show Cajero</h1>

<ul>

  <li>
    <strong>Saldo:</strong>
    <%= @cajero.saldo %>
  </li>

  <li>
    <strong>Retiro:</strong>
    <%= @cajero.retiro %>
  </li>

  <li>
    <strong>Deposito:</strong>
    <%= @cajero.deposito %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.cajero_path(@conn, :edit, @cajero) %></span>
<span><%= link "Back", to: Routes.cajero_path(@conn, :index) %></span>